#include <stddef.h>
#include <Spi_cfg.h>


// This file is autogenerated, any hand modifications will be lost!


const SpiGeneralCfgType SpiGeneralCfg = {
	.spi_level_delivered     = 1,
	.spi_chan_buff_allowed   = SPI_CHAN_TYPE_IB,
	.spi_intr_seq_allowed    = FALSE,
	.spi_hw_status_api       = FALSE,
	.spi_cancel_api          = FALSE,
	.spi_version_info_api    = FALSE,
	.spi_dev_error_detect    = FALSE,
	.spi_supp_conc_sync_tx   = FALSE,
	.spi_main_func_period_ms = 10
};


const SpiExternalDeviceType SpiExternalDeviceCfg[] = {
};



const SpiChannelCfgType SpiChannelCfg[] = {
};


const SpiJobCfgType SpiJobCfg[] = {
};


const SpiSequenceCfgType SpiSequenceCfg[] = {
};


const Spi_ConfigType SpiConfigs = {
	.general   = SpiGeneralCfg,
	.devices   = SpiExternalDeviceCfg,
	.channels  = SpiChannelCfg,
	.jobs      = SpiJobCfg,
	.sequences = SpiSequenceCfg
};

